### PR TITLE
Notify systemd when sbulb is ready #27

### PR DESCRIPTION
**Pull request by oliwer**
I am using suprocess.call() to be backward-compatible with python 2.

### CODE REVIEW

**Comment by sbernard31** [comment]
1. Maybe we can launch it only if sbulb is launched by systemd ? (using https://serverfault.com/a/927481)

2. Currently the input/output/error pipes of  `systemd-notify --ready` is connect to sbulb process. Do we really want this ? If not we could use [`DEVNULL`](https://docs.python.org/3.7/library/subprocess.html#call-function-trio).

3. Should we check if file `systemd-notify` exists before to run with somethink like [`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which)?

**Comment by oliwer** [comment]
1. Good idea. I'll look for `$INVOCATION_ID`.
2. Yes, I want to see any error message raised by `systemd-notify`.
3. That is useless. If the binary is not present, it will just fail silently.

**Comment by sbernard31** [comment]
> 3.  that is useless. If the binary is not present, it will just fail silently.

The only reason I could see would be that we keep `stderr` connected and we launch `systemd-notify` only if "systemd is used" AND "`systemd-notify` is present&executable". So this way we see an output error only if `systemd-notify` failed unexpectedly  :thinking:

**Comment by oliwer** [comment]
I'm going to use the environment variable `$NOTIFY_SOCKET` instead of `$INVOCATION_ID`. This variable is only set if the service has `Type=notify`.
If this variable is set, `systemd-notify` has to be present. If not, I want to see the shell error.

**Pull request merged**
